# 1. Trigger
trigger:
  branches:
    include:
      - main
      - features/*

# 2. Pool (यहाँ आपका Agent Pool जुड़ेगा)
pool:
  name: 'septakhilesh'

# 3. Parameters
parameters:
  - name: runTfSec
    displayName: "Run TfSec?"
    type: boolean
    default: true

  - name: runTfLint
    displayName: "Run TfLint?"
    type: boolean
    default: true

  - name: runCheckov
    displayName: "Run Checkov?"
    type: boolean
    default: true

  - name: runValidate
    displayName: "Run Validate?"
    type: boolean
    default: true

# 4. Variables
variables:
  workingDirectory: 'environments/dev'